config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  devise_for :users
  resources :users
  resources :categories, only: [:index, :new, :create] do
    resources :operations, only: [:index, :new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "splash#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_and_belongs_to_many :operations

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount_category
    total = 0
    operations.each do |operation|
      total += operation.amount
    end
    total.round(2)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories.includes(:categories_operations).includes([:operations])
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= link_to category_operations_path(category) do %>
<div class="categories__card" id="<%= dom_id category %>">
  <img class="categories__card-img" src="<%=asset_path("#{category.icon}.png") %>" >

  <div class="categories__card-info">
    <p>
      <%= category.name %>
    </p>
    <p class="categories__card-info-date">
      <%= category.created_at.strftime("%Y-%m-%d") %>
    </p>
  </div>
  <div class="categories__card-qty">
    <p>
      $ <%= category.total_amount_category %>
    </p>
  </div>
  </div>
<% end %>

app/views/categories/_form.html.erb
<% icon_categories =[
    {
      icon: 'home',
      title: 'home',
    },
    {
      icon: 'transportation',
      title: 'Transportation',
    },
    {
      icon: 'food',
      title: 'food',
    },
    {
      icon: 'utilities',
      title: 'utilities',
    },
    {
      icon: 'clothing',
      title: 'clothing',
    },
    {
      icon: 'medical',
      title: 'medical',
    },
    {
      icon: 'insurance',
      title: 'insurance',
    },
    {
      icon: 'personal',
      title: 'personal',
    },
    {
      icon: 'debt',
      title: 'debt',
    },
    {
      icon: 'retirement',
      title: 'retirement',
    },
    {
      icon: 'education',
      title: 'education',
    },
    
  ] %>

<div class="newcategory__container">
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="newcategory__field">
    <%= form.label :name, style: "display: block", class: 'form__label' %>
    <%= form.text_field :name, class: 'form__input' %>
  </div>
   <p class="newcategory__text">Select an icon from the list</p>
    
    <ul class="newcategory__option">
    
    <% icon_categories.each do |icon_category|%>
      <li class="newcategory__option-list">
        <%= form.radio_button :icon, icon_category[:icon] %> 
        <img class="newcategory__img" src="<%=asset_path("#{icon_category[:icon]}.png") %>" alt=<%=icon_category[:title]%>>
      </li>
       <% end %>
    </ul>
  <div class="newcategory__button">
    <%= form.submit :class => 'btn-solid'%>
  </div>
<% end %>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<%= render "shared/navbar" %>

<p style="color: green"><%= notice %></p>

<div class="categories">
<h2 class="categories__title">Categories:</h2>

<div id="categories" class="categories__container">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>
<div class="categories__button">
<%= link_to "New category", new_category_path, class: "btn-solid"  %>
</div>
</div>

app/views/categories/new.html.erb
<%= render "shared/navbar" %>
<div class="newcategory">
<h2 class="newcategory__title">New category</h2>

<%= render "form", category: @category %>

</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>