config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  devise_for :users
  resources :users
  resources :categories, only: [:index, :new, :create] do
    resources :operations, only: [:index, :new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "splash#index"
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :categories

  validates :name, presence: true
  validates :amount, presence: true
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :authenticate_user!
  before_action :acq_category
  before_action :acq_categories
  before_action :set_operation, only: %i[show edit update destroy]

  # GET /operations or /operations.json
  def index
    @operations = @category.operations.includes(:categories_operations).includes([:categories])
  end

  # GET /operations/1 or /operations/1.json
  def show; end

  # GET /operations/new
  def new
    @operation = current_user.operations.build
  end

  # GET /operations/1/edit
  def edit; end

  # POST /operations or /operations.json
  def create
    @operation = current_user.operations.build(operation_params)
    respond_to do |format|
      if @operation.save
        @operation.categories << acq_categories
        format.html { redirect_to category_operations_path(@category), notice: 'Operation was successfully created.' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_operation
    @operation = Operation.find(params[:id])
  end

  def acq_category
    @category = Category.find(params[:category_id])
  end

  def acq_categories
    categories = []
    selected_category = Category.find(params[:category_id])
    extra_categories = params[:categories] ? Category.where(id: params[:categories][:category_ids]).to_a : []
    categories << selected_category << extra_categories
    categories.flatten
  end

  # Only allow a list of trusted parameters through.
  def operation_params
    params.require(:operation).permit(:name, :amount, :user_id)
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<div class="newoperation__container">
<%= form_with(model: operation, url: category_operations_path(@category)) do |form| %>
  <% if operation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="newcategory__field">
    <%= form.label :name, style: "display: block", class: 'form__label' %>
    <%= form.text_field :name, class: 'form__input' %>
  </div>

  <div class="newcategory__field">
    <%= form.label :amount, style: "display: block", class: 'form__label' %>
    <%= form.number_field :amount, class: 'form__input' %>
  </div>

  <p class="newoperation__text">Extra categories</p>
  
  <ul class="newoperation__option">
  <%= fields_for :categories do |extra_categories| %>
  <%= extra_categories.collection_check_boxes( :category_ids, Category.where(user: current_user), :id, :name, include_hidden: false, class: 'newoperation__check') do |b| %>
  <% if b.value != params[:category_id].to_i %>
    <li>
      <%= b.check_box %>
      <%= b.label %>
    </li>
  <% end %>
  <% end %>
  <%end%>
  </ul>
  <div class="newcategory__button">
    <%= form.submit "Create new transaction", :class => 'btn-solid'%>
  </div>
<% end %>
</div>

app/views/operations/_operation.html.erb
<div class="operations__card" id="<%= dom_id operation %>">
  <div class="operations__card-info">
  <p class="operations__card-info-name">
    <%= operation.name %>
  </p>

  <p class="operations__card-info-qty">
    <strong>Amount: $</strong>
    <%= operation.amount %>
  </p>
  </div>
<div class="operations__card-image">
  <% operation.categories.each do |category| %>
  <%= image_tag("#{category.icon}.png", alt: category.name, class: 'operations__card-image-img') %> 
  <% end %>
  </div>

  <p class="operations__card-footer">
    <strong>Created at:</strong>
    <%= operation.created_at.strftime("%Y-%m-%d") %>
  </p>

</div>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Show this operation", @operation %> |
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/index.html.erb
<%= render "shared/navbar" %>
<p style="color: green"><%= notice %></p>

<div class="operation__category">
<img class="categories__card-img" src="<%=asset_path("#{@category.icon}.png") %>" >
<div>
<p>
<strong>Category:</strong> 
<%= @category.name %>
</p>
<p>
<strong>Total:</strong> 
$ <%= @category.total_amount_category %>
</p>
</div>
</div>

<div class="operations">

<h2 class="operations__title">Transactions</h2>

<div id="operations" class="operations__container">
  <% @operations.each do |operation| %>
    <%= render operation %>

  <% end %>
</div>
<div class="operations__button">
<%= link_to "New transaction", new_category_operation_path(@category), class: "btn-solid" %>
</div>
</div>

app/views/operations/new.html.erb
<%= render "shared/navbar" %>
<div class="newoperation">
<h2 class="newoperation__title">New Transaction</h2>

<%= render "form", operation: @operation %>

</div>

app/views/operations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @operation %>

<div>
  <%= link_to "Edit this operation", edit_operation_path(@operation) %> |
  <%= link_to "Back to operations", operations_path %>

  <%= button_to "Destroy this operation", @operation, method: :delete %>
</div>